repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
#-   repo: https://github.com/psf/black
#    rev: 19.3b0
#    hooks:
#    -   id: black
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: black --check
        language: system
        types: [python]
-   repo: https://github.com/pycqa/pylint
    rev: pylint-2.8.1
    hooks:
    -   id: pylint
